/**
 * docs-sync.js
 *
 * Fetches the latest Three.js API documentation from GitHub every day
 * and writes a structured DOCS.md into the ./docs/ folder.
 * Runs automatically in the background whenever the MCP server is running.
 */

import cron from 'node-cron';
import fetch from 'node-fetch';
import fs from 'fs/promises';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const DOCS_DIR = path.join(__dirname, '..', 'docs');
const DOCS_FILE = path.join(DOCS_DIR, 'API.md');
const META_FILE = path.join(DOCS_DIR, '.sync-meta.json');

// Three.js GitHub raw content base
const GITHUB_RAW = 'https://raw.githubusercontent.com/mrdoob/three.js/master';
const GITHUB_API = 'https://api.github.com/repos/mrdoob/three.js/contents/docs/api/en';

// All Three.js doc categories and their subdirectories
const DOC_CATEGORIES = [
  { name: 'Animation',       path: 'animation' },
  { name: 'Audio',           path: 'audio' },
  { name: 'Cameras',         path: 'cameras' },
  { name: 'Constants',       path: 'constants' },
  { name: 'Core',            path: 'core' },
  { name: 'Extras',          path: 'extras' },
  { name: 'Geometries',      path: 'geometries' },
  { name: 'Helpers',         path: 'helpers' },
  { name: 'Lights',          path: 'lights' },
  { name: 'Lights / Shadows',path: 'lights/shadows' },
  { name: 'Loaders',         path: 'loaders' },
  { name: 'Materials',       path: 'materials' },
  { name: 'Math',            path: 'math' },
  { name: 'Objects',         path: 'objects' },
  { name: 'Renderers',       path: 'renderers' },
  { name: 'Scenes',          path: 'scenes' },
  { name: 'Textures',        path: 'textures' }
];

/**
 * Fetch directory listing from GitHub API
 */
async function fetchDirListing(subPath) {
  const url = subPath ? `${GITHUB_API}/${subPath}` : GITHUB_API;
  const res = await fetch(url, {
    headers: { 'Accept': 'application/vnd.github.v3+json', 'User-Agent': 'threejs-mcp-docs-sync' }
  });
  if (!res.ok) return [];
  const data = await res.json();
  return Array.isArray(data) ? data.filter(f => f.name.endsWith('.html')) : [];
}

/**
 * Fetch raw HTML doc and extract class name, description, constructor, properties, methods
 */
async function parseDocPage(rawUrl, className) {
  try {
    const res = await fetch(rawUrl, { headers: { 'User-Agent': 'threejs-mcp-docs-sync' } });
    if (!res.ok) return null;
    const html = await res.text();

    // Extract description (first <p> content)
    const descMatch = html.match(/<p[^>]*>([\s\S]*?)<\/p>/);
    const description = descMatch
      ? descMatch[1].replace(/<[^>]+>/g, '').replace(/\s+/g, ' ').trim()
      : 'No description available.';

    // Extract constructor signature
    const ctorMatch = html.match(/\[name\]\s*\(([^)]*)\)/);
    const constructor = ctorMatch ? `new THREE.${className}(${ctorMatch[1]})` : `new THREE.${className}()`;

    // Extract properties: [property:Type name]
    const propPattern = /\[property:([^\]]+)\s+([^\]]+)\]/g;
    const properties = [];
    let m;
    while ((m = propPattern.exec(html)) !== null) {
      properties.push(`- \`${m[2].trim()}\`: ${m[1].trim()}`);
    }

    // Extract methods: [method:Type name]
    const methodPattern = /\[method:([^\]]+)\s+([^\]]+)\]\s*\(([^)]*)\)/g;
    const methods = [];
    while ((m = methodPattern.exec(html)) !== null) {
      methods.push(`- \`.${m[2].trim()}(${m[3].trim()})\` → ${m[1].trim()}`);
    }

    return { className, description, constructor, properties, methods };
  } catch {
    return null;
  }
}

/**
 * Build the full DOCS.md content
 */
async function buildDocs() {
  const now = new Date();
  let md = `# Three.js API Reference\n\n`;
  md += `> Auto-generated by threejs-mcp docs-sync | Last updated: **${now.toUTCString()}**\n\n`;
  md += `> Source: [mrdoob/three.js](https://github.com/mrdoob/three.js) | Docs: [threejs.org/docs](https://threejs.org/docs)\n\n`;
  md += `---\n\n## Table of Contents\n\n`;

  const toc = DOC_CATEGORIES.map(c => `- [${c.name}](#${c.name.toLowerCase().replace(/[\s\/]+/g, '-')})`).join('\n');
  md += toc + '\n\n---\n\n';

  for (const category of DOC_CATEGORIES) {
    md += `## ${category.name}\n\n`;
    const files = await fetchDirListing(category.path);

    if (files.length === 0) {
      md += `_No pages found for this category._\n\n`;
      continue;
    }

    for (const file of files) {
      const className = file.name.replace('.html', '');
      const rawUrl = `${GITHUB_RAW}/docs/api/en/${category.path}/${file.name}`;
      const doc = await parseDocPage(rawUrl, className);

      if (!doc) {
        md += `### ${className}\n\n_Failed to load documentation._\n\n`;
        continue;
      }

      md += `### ${doc.className}\n\n`;
      md += `**Description:** ${doc.description}\n\n`;
      md += `**Constructor:** \`${doc.constructor}\`\n\n`;

      if (doc.properties.length > 0) {
        md += `**Properties:**\n${doc.properties.join('\n')}\n\n`;
      }

      if (doc.methods.length > 0) {
        md += `**Methods:**\n${doc.methods.join('\n')}\n\n`;
      }

      md += `**Docs:** [threejs.org/docs/${category.path}/${className}](https://threejs.org/docs/#api/en/${category.path}/${className})\n\n`;
      md += `---\n\n`;

      // Small delay to be polite to GitHub
      await new Promise(r => setTimeout(r, 80));
    }
  }

  return md;
}

/**
 * Run a full sync cycle
 */
async function runSync() {
  console.log('[docs-sync] Starting Three.js docs sync...');
  const start = Date.now();

  try {
    await fs.mkdir(DOCS_DIR, { recursive: true });
    const content = await buildDocs();
    await fs.writeFile(DOCS_FILE, content, 'utf8');

    const meta = {
      lastSync: new Date().toISOString(),
      durationMs: Date.now() - start,
      sizeBytes: Buffer.byteLength(content, 'utf8')
    };
    await fs.writeFile(META_FILE, JSON.stringify(meta, null, 2), 'utf8');

    console.log(`[docs-sync] ✅ Docs synced in ${meta.durationMs}ms — ${Math.round(meta.sizeBytes / 1024)}KB written to ${DOCS_FILE}`);
  } catch (err) {
    console.error('[docs-sync] ❌ Sync failed:', err.message);
  }
}

/**
 * Check if docs are stale (older than 24h)
 */
async function isStale() {
  try {
    const raw = await fs.readFile(META_FILE, 'utf8');
    const meta = JSON.parse(raw);
    const age = Date.now() - new Date(meta.lastSync).getTime();
    return age > 23 * 60 * 60 * 1000; // 23 hours
  } catch {
    return true; // no meta = first run
  }
}

/**
 * Start the docs sync scheduler.
 * - Runs immediately if docs are stale (first run or >23h old)
 * - Schedules daily at 2:00 AM UTC
 */
export async function startDocsSync() {
  // Run immediately if stale
  if (await isStale()) {
    await runSync();
  } else {
    try {
      const raw = await fs.readFile(META_FILE, 'utf8');
      const meta = JSON.parse(raw);
      console.log(`[docs-sync] Docs are fresh (last synced: ${meta.lastSync}). Next sync at 02:00 UTC.`);
    } catch {
      await runSync();
    }
  }

  // Schedule daily at 2:00 AM UTC
  cron.schedule('0 2 * * *', async () => {
    console.log('[docs-sync] ⏰ Daily cron triggered');
    await runSync();
  }, { timezone: 'UTC' });

  console.log('[docs-sync] 📅 Daily docs sync scheduled at 02:00 UTC');
}

/**
 * MCP tool: force a manual docs refresh
 */
export async function forceSync() {
  await runSync();
  return `Docs sync complete. Written to ${DOCS_FILE}`;
}

/**
 * MCP tool: get docs sync status
 */
export async function getSyncStatus() {
  try {
    const raw = await fs.readFile(META_FILE, 'utf8');
    const meta = JSON.parse(raw);
    const ageMinutes = Math.round((Date.now() - new Date(meta.lastSync).getTime()) / 60000);
    return `Last sync: ${meta.lastSync}\nAge: ${ageMinutes} minutes\nDuration: ${meta.durationMs}ms\nSize: ${Math.round(meta.sizeBytes / 1024)}KB\nDocs path: ${DOCS_FILE}`;
  } catch {
    return 'Docs have never been synced. Use force_docs_sync to trigger.';
  }
}

/**
 * MCP tool: search the local docs
 */
export async function searchDocs(query) {
  try {
    const content = await fs.readFile(DOCS_FILE, 'utf8');
    const lines = content.split('\n');
    const results = [];
    let currentSection = '';

    for (const line of lines) {
      if (line.startsWith('### ')) currentSection = line.replace('### ', '');
      if (line.toLowerCase().includes(query.toLowerCase())) {
        results.push(`[${currentSection}] ${line.trim()}`);
      }
    }

    if (results.length === 0) return `No results found for "${query}" in Three.js docs.`;
    return results.slice(0, 20).join('\n');
  } catch {
    return 'Docs file not found. Run force_docs_sync first.';
  }
}
